import 'package:flutter/material.dart';
import 'garden_model.dart';
import 'garden_service.dart';
import 'garden_detail_screen.dart';

class GardensScreen extends StatelessWidget {
  const GardensScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final GardenService gardenService = GardenService();

    return Scaffold(
      body: StreamBuilder<List<Garden>>(
        stream: gardenService.getGardensStream(),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return Center(child: Text('Error: ${snapshot.error}'));
          }
          if (!snapshot.hasData) {
            return const Center(child: CircularProgressIndicator());
          }

          final gardens = snapshot.data!;
          if (gardens.isEmpty) {
            return const Center(
              child: Text(
                'No gardens yet. Add one!',
                style: TextStyle(fontSize: 24, color: Colors.grey),
              ),
            );
          }

          return ListView.builder(
            padding: const EdgeInsets.all(16.0),
            itemCount: gardens.length,
            itemBuilder: (context, index) {
              final garden = gardens[index];
              return _buildGardenCard(context, garden);
            },
          );
        },
      ),
      floatingActionButton: SizedBox(
        width: 80,
        height: 80,
        child: FloatingActionButton(
          onPressed: () => _showAddGardenDialog(context, gardenService),
          backgroundColor: Theme.of(context).colorScheme.primary,
          child: const Icon(Icons.add, size: 40, color: Colors.white),
        ),
      ),
    );
  }

  Widget _buildGardenCard(BuildContext context, Garden garden) {
    return Card(
      margin: const EdgeInsets.only(bottom: 16),
      elevation: 4,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: InkWell(
        onTap: () {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => GardenDetailScreen(garden: garden),
            ),
          );
        },
        borderRadius: BorderRadius.circular(16),
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: Row(
            children: [
              const Icon(Icons.yard, size: 50, color: Colors.green),
              const SizedBox(width: 24),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      garden.name,
                      style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                            fontWeight: FontWeight.bold,
                          ),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      '${garden.zones.length} zones',
                      style: Theme.of(context).textTheme.titleMedium?.copyWith(
                            color: Colors.grey[700],
                            fontSize: 20,
                          ),
                    ),
                  ],
                ),
              ),
              const Icon(Icons.chevron_right, size: 40, color: Colors.grey),
            ],
          ),
        ),
      ),
    );
  }

  void _showAddGardenDialog(BuildContext context, GardenService service) {
    final TextEditingController nameController = TextEditingController();

    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('New Garden'),
          content: TextField(
            controller: nameController,
            decoration: const InputDecoration(
              labelText: 'Garden Name',
              hintText: 'e.g., Big Garden',
            ),
            autofocus: true,
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Cancel', style: TextStyle(fontSize: 20)),
            ),
            ElevatedButton(
              onPressed: () {
                if (nameController.text.isNotEmpty) {
                  final newGarden = Garden(
                    id: '', // ID generated by Firestore
                    name: nameController.text,
                    zones: [],
                  );
                  service.addGarden(newGarden);
                  Navigator.pop(context);
                }
              },
              child: const Text('Add', style: TextStyle(fontSize: 20)),
            ),
          ],
        );
      },
    );
  }
}
