// File generated by Antigravity based on user provided config.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrq6APPrTHmo0JqmTVj-nKNhMkMAxa7dg',
    appId: '1:895730760806:web:7f649398366ff1f7f7c1a7',
    messagingSenderId: '895730760806',
    projectId: 'homestead-companion',
    authDomain: 'homestead-companion.firebaseapp.com',
    storageBucket: 'homestead-companion.firebasestorage.app',
  );
}
